#!/usr/bin/env python

import unittest
from fizzbuzz import FizzBuzz

class TestFizzBuzz(unittest.TestCase):
  def test_numeroNormal(self):
  	self.assertEqual(FizzBuzz(1), 1) 
    self.assertEqual(FizzBuzz(2), 2)
    self.assertEqual(FizzBuzz(4), 4)
    
  def test_numeroMult3(self):
    self.assertEqual(FizzBuzz(3), "fizz")
    self.assertEqual(FizzBuzz(9), "fizz")
  
if __name__ == '__main__':
  unittest.main()

======================//==========================

#!/usr/bin/env python
 
def FizzBuzz(numero):
  if (numero % 3 == 0):
  #if not numero % 3:
		return "fizz"
    
	return numero
  
  
# return not numero % 3

  

LISTA DE ESPECIFICAÇÃO -- >>

*FizzBuzz recebe um número  OK
*FizzBuzz(1) return 1       OK
*FizzBuzz(2) return 2       OK
*FizzBuzz(3) return 'fizz'  OK
*FizzBuzz(4) return 4       OK
*FizzBuzz(5) return 'buzz'
...
*FizzBuzz(9) return 'fizz'
...
*FizzBuzz(15) return 'fizz buzz'
